[package]
name = "twitch-rpg-client"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.2", features = ["csr"]}
console_error_panic_hook = "0.1.7"
web-sys = {version = "0.3.77", features = ["Window", "CanvasRenderingContext2d"]}
wasm-bindgen = "0.2.100"