[workspace]
members = [
    "frontend",
#    "webserver",
#    "game",
    "twitch-rpg-irc",
]

resolver = "2"

[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false
panic = "abort"

