[package]
name = "twitch-rpg-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tatami-dungeon = "0.1.7"
assets_manager = { version = "0.13.0", features = ["ron"] }