use common::{AttackModifiers, DefenseModifiers, EquipmentSlot, ItemQuality, ItemStats, OtherModifiers, ShopItem};

#[derive(Default)]
pub struct ShopItemPool {
    pub all_items: Vec<ShopItem>,
}

pub fn initialize_shop_items() -> Vec<ShopItem> {
    vec![
        ShopItem {
            sprite: "white_wizard_hat".to_string(),
            name: "Academy Teacher's Hat".to_string(),
            quality: ItemQuality::Legendary,
            equip_slot: EquipmentSlot::Head,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: Some(DefenseModifiers{ damage_reduction: 1, evasion_rating: 0}),
                other_modifiers: None,

                strength: None,
                intelligence: Some(9),
                dexterity: None,
            },
            price: 230,
            description: "Spells have longer durations and affect larger areas".to_string(),
        },
        ShopItem {
            sprite: "mace".to_string(),
            name: "Mace".to_string(),
            quality: ItemQuality::Common,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: Some(AttackModifiers{
                    damage_bonus: 1,
                    hit_rating_bonus: 3,
                    range_bonus: 0,
                    cooldown_reduction_ms: 0,
                }),
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 15,
            description: "Staggers opponents on hit".to_string(),
        },
        ShopItem {
            sprite: "trident".to_string(),
            name: "Trident".to_string(),
            quality: ItemQuality::Uncommon,
            equip_slot: EquipmentSlot::MainHand,

            price: 18,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            description: "Melee attacks have longer reach".to_string(),
        },
        ShopItem {
            sprite: "trident".to_string(),
            name: "Trident".to_string(),
            quality: ItemQuality::Common,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 18,
            description: "Melee attacks have longer reach".to_string(),
        },
        ShopItem {
            sprite: "greatsword".to_string(),
            name: "Greatsword".to_string(),
            quality: ItemQuality::Uncommon,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: Some(AttackModifiers{
                    damage_bonus: 3,
                    hit_rating_bonus: 2,
                    range_bonus: 2,
                    cooldown_reduction_ms: 0,
                }),
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 28,
            description: "Melee attacks have longer reach".to_string(),
        },
        ShopItem {
            sprite: "longsword".to_string(),
            name: "Longsword".to_string(),
            quality: ItemQuality::Rare,
            equip_slot: EquipmentSlot::Head,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 34,
            description: "Melee attacks have longer reach".to_string(),
        },
        ShopItem {
            sprite: "scimitar".to_string(),
            name: "Scimitar".to_string(),
            quality: ItemQuality::Uncommon,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 20,
            description: "Melee attacks cut deeper".to_string(),
        },
        ShopItem {
            sprite: "purple_tip_wood_staff".to_string(),
            name: "Netherwood Staff".to_string(),
            quality: ItemQuality::Uncommon,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 20,
            description: "Curses last longer".to_string(),
        },
        ShopItem {
            sprite: "purple_tip_silver_staff".to_string(),
            name: "Nether-orb Staff".to_string(),
            quality: ItemQuality::Rare,
            equip_slot: EquipmentSlot::MainHand,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: None,
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 40,
            description: "More elemental damage".to_string(),
        },
        ShopItem {
            sprite: "red_cloth_boots".to_string(),
            name: "Cinder Slippers".to_string(),
            quality: ItemQuality::Rare,
            equip_slot: EquipmentSlot::Feet,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: Some(OtherModifiers{ movement_speed_increase: 1 }),
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 40,
            description: "More elemental resistance".to_string(),
        },
        ShopItem {
            sprite: "green_leather_boots".to_string(),
            name: "Elven Boots".to_string(),
            quality: ItemQuality::Uncommon,
            equip_slot: EquipmentSlot::Head,
            stats: ItemStats {
                attack_modifiers: None,
                defense_modifiers: None,
                other_modifiers: Some(OtherModifiers{ movement_speed_increase: 5 }),
                strength: None,
                intelligence: None,
                dexterity: None,
            },
            price: 30,
            description: "More movement speed".to_string(),
        },
    ]
}
